use_frameworks!

target 'DataSourcerer_Example' do
  pod 'DataSourcerer', :path => '../'

  target 'DataSourcerer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
