use_frameworks!

target 'DataSourcerer_Example' do
  pod 'DataSourcerer', :path => '../'

  target 'DataSourcerer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'SwiftLint'
    pod 'Reveal-SDK', '19', :configurations => ['Debug'] # view hierarchy inspection
  end
end
